import Head from 'next/head';
import { dehydrate, QueryClient, useQuery } from '@tanstack/react-query';
import { getCatFact } from './api/catCall';

export async function getStaticProps() {
  try {
    const queryClient = new QueryClient();
    await queryClient.prefetchQuery(['catfacts'], getCatFact);
    console.log('hello');
    return {
      props: {
        dehydratedState: dehydrate(queryClient),
      },
      revalidate: 5,
    };
  } catch (error) {
    return {
      props: {
        error: true,
      },
    };
  }
}

export default function Home(
 { dehydratedState, error }
) {
  console.log('dehydrateed', dehydratedState);
  if (error) {
    return <div>sorry we encountered a unexpected error</div>;
  } 
  if (!dehydratedState.queries || dehydratedState.queries.length < 1) {
    return <div>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>On mate quoi ?</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="m-8 flex h-24 border-2 border-red-600  bg-primary p-3 lg:m-4 lg:p-4">
          Welcome to another <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className="bg-orange-600 text-2xl text-red-900">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Itaque distinctio, quos temporibus quas repellat voluptate consequuntur laboriosam facere consectetur laudantium?</p>
      </main>
    </>
  );
}
