import Head from 'next/head';
import Image from 'next/image';
import {  QueryClient, useQuery, dehydrate } from '@tanstack/react-query';
import { getCatFact, getMoviePosters } from './api/TMDBMoviesCall';
import { Suspense, lazy, useState } from 'react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { useRouter } from 'next/router';

export async function getServerSideProps() {
	try {
		const queryClient = new QueryClient();
		await queryClient.prefetchQuery(['moviePosters'], getMoviePosters);
		console.log('hello');
		return {
			props: {
				dehydratedState: dehydrate(queryClient),
			},
		};
	} catch (error) {
		return {
			props: {
				error: true,
			},
		};
	}
}

export default function Home(dehydratedState) {
	const router = useRouter();
	console.log(dehydratedState);
	const posterArray = dehydratedState.dehydratedState.queries[0].state.data;
	console.log(posterArray);
	const baseUrlForPoster = 'https://image.tmdb.org/t/p/w300';
	return (
		<>
			<Head>
				<title>On mate quoi ?</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.png" />
			</Head>
			<main className='flex h-[100vh] flex-col items-center justify-start bg-yellow-50'>
				<Header />
				<div className="grid grid-cols-5 grid-rows-4 gap-2">
  {posterArray.map((poster, index) => (
    <div key={index} className={`h-32 w-32 bg-metalgrey col-start-${(index % 5) + 1} row-start-${Math.floor(index / 5) + 1}`}>
      <img src={baseUrlForPoster + poster} alt=""  />
    </div>
  ))}
</div>
				  <button onClick={() => {router.push('/questions');}} className="m-12 bg-metalgrey py-12 px-56 text-white">
				  Show Film Titles
				  </button>

				<Footer />
			</main>
		</>
	);
}
