import Head from 'next/head';
import Image from 'next/image';
import {  QueryClient, useQuery } from '@tanstack/react-query';
import { getCatFact } from './api/catCall';
import { Suspense, lazy, useState } from 'react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Link from 'next/link';
// import FilmTitles from '@/components/FilmTitles';

export default function Home() {
	return (
		<>
			<Head>
				<title>On mate quoi ?</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.png" />
			</Head>
			<main className='flex h-[100vh] flex-col items-center justify-start bg-yellow-50'>
				<Header />
				<div className='image-cover flex w-[70vw] flex-1 flex-col items-center justify-center bg-red-500'>
					<Link href="/questions">
        
				  <button onClick={() => {
							console.log('click');
						}

						} className="m-12 bg-metalgrey py-12 px-56 text-white">Show Film Titles</button>

						{/* <div className='my-12 flex items-center justify-center'>
					<Image src="/canape-movie.png" alt="" width={1100} height={1200} />
				</div> */}
					</Link>
				</div>
				<Footer />
			</main>
		</>
	);
}
